apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: copy-secrets-to-ephemeral-cluster
spec:
  description: >-
    This Task copies Secrets from the current namespace into a configurable namespace on an
    ephemeral cluster. The name and content of each Secret is unaltered in the process.
  params:
  - name: clusterCredentialsSecretRef
    type: string
    description: >-
      Name of the Secret containing kubeconfig and password to access the provisioned ephemeral cluster
  - name: namespace
    type: string
    description: The destination namespace for the secrets. The namespace must already exist.
  - name: labelSelector
    type: string
    description: A label selector identifying the secrets to be copied
  steps:
  - name: copy-secrets
    image: quay.io/konflux-ci/konflux-test:v1.4.52@sha256:aa2c97da9bb73a4e8d1c6b41950f8d902b74461be0e042debe89277fdc4ebe49
    env:
    - name: KUBECONFIG_VALUE
      valueFrom:
        secretKeyRef:
          name: $(params.clusterCredentialsSecretRef)
          key: kubeconfig
    - name: NAMESPACE
      value: $(params.namespace)
    - name: LABEL_SELECTOR
      value: $(params.labelSelector)
    script: |
      #!/bin/bash
      set -eo pipefail

      DEST_KUBECONFIG="$(mktemp /tmp/kubeconfig.XXXXX)"
      echo "$KUBECONFIG_VALUE" >"$DEST_KUBECONFIG"

      oc get secrets -l "$LABEL_SELECTOR" -o json \
        | jq --arg ns "$NAMESPACE" '.items[].metadata.namespace=$ns' \
        | jq 'del(.items[] | .metadata.creationTimestamp,
                  .metadata.uid, .metadata.resourceVersion,
                  .metadata.annotations."kubectl.kubernetes.io/last-applied-configuration")' \
        | oc apply --kubeconfig="$DEST_KUBECONFIG" -f -
